- hosts: slaves
  become: yes
  become_user: root
  tasks:
   - name: Install JRE
     apt:
       name: default-jre
       state: installed
       update_cache: true

   - name: Install JDK
       apt:
         name: default-jdk
         state: installed
         update_cache: true

